server:
  port: 8086

spring:
  application:
    name: admin-monitoring-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: admin-monitor-group

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.sentinelx.events.fraud.FraudAlertEvent



  datasource:
    url: jdbc:postgresql://localhost:5433/sentinelx
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true