server:
  port: 8083

spring:
  application:
    name: transaction-service

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update