server:
  port: 8084

spring:
  application:
    name: fraud-detection-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: fraud-group
      auto-offset-reset: earliest