server:
  port: 8084

spring:
  application:
    name: fraud-detection-service

  datasource:
    url: jdbc:postgresql://localhost:5433/sentinelx
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: fraud-group
      auto-offset-reset: earliest

  data:
    redis:
      host: localhost
      port: 6379